version: 2.1

requires_prepared_code: &requires_prepared_code
  requires:
  - prepare_code

common_tags_filter: &common_tags_filter
  filters:
    tags:
      only: /^v.*/

# Workflow definition
workflows:
  version: 2

  test_and_release:
    jobs:
    - prepare_code:
        <<: *common_tags_filter
    - build_darwin_mruby:
        <<: *common_tags_filter
    - prepare_mruby:
        <<: *requires_prepared_code
        <<: *common_tags_filter
    - test:
        <<: *common_tags_filter
        requires:
        - prepare_mruby
    - benchmark:
        <<: *common_tags_filter
        requires:
        - prepare_mruby
    - build_binary_for_conformance:
        <<: *requires_prepared_code
        <<: *common_tags_filter
    - build:
        <<: *requires_prepared_code
        <<: *common_tags_filter
    - build_linux_mruby:
        <<: *common_tags_filter
        requires:
        - prepare_mruby
    - conformance:
        <<: *common_tags_filter
        requires:
        - build_binary_for_conformance
    - conformance_v1:
        <<: *common_tags_filter
        requires:
        - conformance
    - build_docker:
        requires:
        - test
        - conformance
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - build_docker_alpine:
        requires:
        - test
        - conformance
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - build_docker_mruby:
        requires:
        - test
        - conformance
        - build_linux_mruby
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - github_release:
        requires:
        - test
        - conformance
        - build
        - build_linux_mruby
        - build_darwin_mruby
        filters:
          tags:
            only: /^v[0-9]+\.[0-9]+\.[0-9]+((\-|\.)(preview|beta|rc)\d+)?$/
          branches:
            ignore: /.*/

executors:
  golang:
    docker:
      - image: circleci/golang:1.12.4-stretch
    working_directory: /go/src/github.com/anycable/anycable-go/
    environment:
      CGO_ENABLED: "0"
      GO111MODULE: "on"
      GOFLAGS: "-mod=vendor"
  osx:
    macos:
      xcode: "10.0.0"
    environment:
      GOPATH: /Users/distiller/go
      CGO_ENABLED: "1"
      GO111MODULE: "on"
      GOFLAGS: "-mod=vendor"
      GO_VERSION: 1.12.4
      GO_SHA: 5b3c6aafd31746809e2776c685e89190f85307074e48af2681d472f8a6a3c504
    working_directory: /Users/distiller/go/src/github.com/anycable/anycable-go/
  docker:
    docker:
      - image: docker:18.06.0-ce
    working_directory: /root/project/
  ruby:
    docker:
      - image: circleci/ruby:2.5-stretch

commands:
  build:
    description: Build AnyCable Go binary
    parameters:
      os:
        type: string
      arch:
        type: string
      postfix:
        type: string
    steps:
      - run: env GOOS=<< parameters.os >> GOARCH=<< parameters.arch >> go build -ldflags "-s -w -X main.version=$(git describe --tags)" -a -o "/tmp/dist/anycable-go-<< parameters.postfix >>" cmd/anycable-go/main.go
  build-mruby:
    description: Build AnyCable Go binary with mruby support
    parameters:
      os:
        type: string
      arch:
        type: string
      postfix:
        type: string
    steps:
      - run: env GOOS=<< parameters.os >> GOARCH=<< parameters.arch >> go build -ldflags "-s -w -X main.version=$(git describe --tags)-mrb" -tags mrb -a -o "/tmp/dist/anycable-go-<< parameters.postfix >>" cmd/anycable-go/main.go

# Jobs definitions
jobs:
  prepare_code:
    executor: golang
    steps:
    - attach_workspace:
        at: .
    - checkout
    - persist_to_workspace:
        root: .
        paths: .

  prepare_mruby:
    executor: ruby
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Install bison
        command: |
          sudo apt update && \
          sudo apt -y install bison
    - run:
        name: Build libmruby.a
        command: bash -c '(cd vendor/github.com/mitchellh/go-mruby && MRUBY_CONFIG=../../../../../../etc/build_config.rb make libmruby.a)'
    - persist_to_workspace:
        root: .
        paths:
        - ./vendor/github.com/mitchellh/go-mruby/vendor/
        - ./vendor/github.com/mitchellh/go-mruby/libmruby.a

  test:
    executor: golang
    environment:
      CGO_ENABLED: "1"
    steps:
    - attach_workspace:
        at: /go/src/github.com/anycable/anycable-go/
    - run: make test
    - run: make vet
    - run: make fmt

  benchmark:
    executor: golang
    environment:
      CGO_ENABLED: "1"
    steps:
    - attach_workspace:
        at: /go/src/github.com/anycable/anycable-go/
    - run: env GO111MODULE=off go get github.com/anycable/websocket-bench
    - run: make build-gobench
    - run:
        command: dist/gobench-cable
        background: true
    - run:
        name: Wait for gobench cable
        command: dockerize -wait tcp://localhost:8080 -timeout 5s
    - run:
        command: websocket-bench broadcast --concurrent 40 --sample-size 100 --step-size 200 --payload-padding 200 --total-steps 5 ws://localhost:8080/cable --server-type=actioncable

  build_binary_for_conformance:
    executor: golang
    steps:
    - attach_workspace:
        at: /go/src/github.com/anycable/anycable-go/
    - run:
        name: Building Linux amd64 binary
        command: go build -ldflags "-s -w -X main.version=$(git describe --tags)" -a -o "/tmp/anycable-go-test" cmd/anycable-go/main.go
    - save_cache:
        key: binary-for-conformance-{{ .Revision }}
        paths: /tmp/anycable-go-test

  build_darwin_mruby:
    executor: osx
    steps:
    - run: mkdir -p ${GOPATH}/src/github.com/anycable/anycable-go/
    - checkout
    - run:
        name: Installing Golang
        command: |
          curl -o go.pkg https://dl.google.com/go/go${GO_VERSION}.darwin-amd64.pkg && \
          echo "${GO_SHA}  go.pkg" | shasum -a 256 -c - && \
          sudo installer -pkg go.pkg -target /
    - run:
        name: Add Go binaries to PATH
        command: echo 'export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"' >> $BASH_ENV
    - run:
        name: Prepare code for the build
        command: |
          bash -c "(cd vendor/github.com/mitchellh/go-mruby && MRUBY_CONFIG=../../../../../../etc/build_config.rb make libmruby.a)"
    - build-mruby:
        os: darwin
        arch: amd64
        postfix: mrb-dawrin-amd64
    - save_cache:
        key: darwin-mruby-{{ .Revision }}
        paths: /tmp/dist/

  build:
    executor: golang
    steps:
    - attach_workspace:
        at: /go/src/github.com/anycable/anycable-go/
    - build:
        os: linux
        arch: "386"
        postfix: linux-386
    - build:
        os: linux
        arch: amd64
        postfix: linux-amd64
    - build:
        os: linux
        arch: arm
        postfix: linux-arm
    - build:
        os: linux
        arch: arm64
        postfix: linux-arm64
    - build:
        os: windows
        arch: "386"
        postfix: win-386
    - build:
        os: windows
        arch: amd64
        postfix: win-amd64
    - build:
        os: darwin
        arch: "386"
        postfix: darwin-386
    - build:
        os: darwin
        arch: amd64
        postfix: darwin-amd64
    - build:
        os: freebsd
        arch: "386"
        postfix: freebsd-386
    - build:
        os: freebsd
        arch: amd64
        postfix: freebsd-amd64
    - build:
        os: freebsd
        arch: arm
        postfix: freebsd-arm
    - save_cache:
        key: build-{{ .Revision }}
        paths: /tmp/dist/

  build_linux_mruby:
    executor: golang
    environment:
      CGO_ENABLED: "1"
    steps:
    - attach_workspace:
        at: /go/src/github.com/anycable/anycable-go/
    - build-mruby:
        os: linux
        arch: amd64
        postfix: mrb-linux-amd64
    - save_cache:
        key: linux-mruby-{{ .Revision }}
        paths: /tmp/dist/

  conformance:
    docker:
    - image: circleci/ruby:2.5.1-stretch
    - image: circleci/redis:4.0.11-alpine3.8
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        key: binary-for-conformance-{{ .Revision }}
    - run:
        name: Install gem anyt (conformance testing tool)
        command: gem install anyt -v '~> 0.8.0'
    - run:
        name: Wait for Redis
        command: dockerize -wait tcp://localhost:6379 -timeout 1m
    - run: anyt -c "/tmp/anycable-go-test --headers=cookie,x-api-token" --target-url="ws://localhost:8080/cable"
    - run: anyt -c "/tmp/anycable-go-test --headers=cookie,x-api-token --ssl_key=etc/ssl/server.key --ssl_cert=etc/ssl/server.crt --port=8443" --target-url="wss://localhost:8443/cable"

  conformance_v1:
    docker:
    - image: circleci/ruby:2.6.3-stretch
    - image: circleci/redis:4.0.11-alpine3.8
    environment:
      BUNDLE_GEMFILE: ".circleci/Gemfile"
    steps:
    - attach_workspace:
        at: .
    - restore_cache:
        key: binary-for-conformance-{{ .Revision }}
    - run:
        name: Install deps
        command: bundle install
    - run:
        name: Wait for Redis
        command: dockerize -wait tcp://localhost:6379 -timeout 1m
    - run: bundle exec anyt -c "/tmp/anycable-go-test --headers=cookie,x-api-token" --target-url="ws://localhost:8080/cable"
    - run: bundle exec anyt -c "/tmp/anycable-go-test --headers=cookie,x-api-token --ssl_key=etc/ssl/server.key --ssl_cert=etc/ssl/server.crt --port=8443" --target-url="wss://localhost:8443/cable"

  build_docker:
    executor: docker
    steps:
    - setup_remote_docker:
        version: 18.06.0-ce
    - attach_workspace:
        at: .
    - restore_cache:
        key: build-{{ .Revision }}
    - run:
        name: Prepare files for Docker build
        command: |
          cp /etc/ssl/certs/ca-certificates.crt ./.docker/ca-certificates.crt && \
          cp /tmp/dist/anycable-go-linux-amd64 .docker/anycable-go-linux-amd64
    - run:
        name: Build Docker image
        command: docker build -f .docker/Dockerfile.linux-amd64 -t anycable/anycable-go:${CIRCLE_TAG/v/''} ./
    - run:
        name: Login to Docker registry
        command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - run:
        name: Push Docker image
        command: docker push anycable/anycable-go:${CIRCLE_TAG/v/''}
    - run:
        name: Push the latest Docker image
        command: |
          if [[ "${CIRCLE_TAG}" == "$(git tag -l --sort=-version:refname "v*" | head -n1)" ]]
          then
              docker tag anycable/anycable-go:${CIRCLE_TAG/v/''} anycable/anycable-go:latest
              docker push anycable/anycable-go:latest
          fi

  build_docker_alpine:
    executor: docker
    steps:
    - setup_remote_docker:
        version: 18.06.0-ce
    - attach_workspace:
        at: .
    - restore_cache:
        key: build-{{ .Revision }}
    - run:
        name: Prepare files for Docker build
        command: |
          cp /etc/ssl/certs/ca-certificates.crt ./.docker/ca-certificates.crt && \
          cp /tmp/dist/anycable-go-linux-amd64 .docker/anycable-go-linux-amd64
    - run:
        name: Build Docker image
        command: docker build -f .docker/Dockerfile.alpine-linux-amd64 -t anycable/anycable-go:${CIRCLE_TAG/v/''}-alpine ./
    - run:
        name: Login to Docker registry
        command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - run:
        name: Push Docker image
        command: docker push anycable/anycable-go:${CIRCLE_TAG/v/''}-alpine

  build_docker_mruby:
    executor: docker
    steps:
    - setup_remote_docker:
        version: 18.06.0-ce
    - attach_workspace:
        at: .
    - restore_cache:
        key: linux-mruby-{{ .Revision }}
    - run:
        name: Prepare binary
        command:
          cp /tmp/dist/anycable-go-mrb-linux-amd64 .docker/anycable-go-mrb-linux-amd64
    - run:
        name: Build Docker image
        command: docker build -f .docker/Dockerfile.mrb-linux-amd64 -t anycable/anycable-go:${CIRCLE_TAG/v/''}-mrb ./
    - run:
        name: Login to Docker registry
        command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - run:
        name: Push Docker image
        command: docker push anycable/anycable-go:${CIRCLE_TAG/v/''}-mrb

  github_release:
    executor: golang
    working_directory: /tmp/dist/
    steps:
    - restore_cache:
        key: darwin-mruby-{{ .Revision }}
    - restore_cache:
        key: linux-mruby-{{ .Revision }}
    - restore_cache:
        key: build-{{ .Revision }}
    - run:
        name: Generate SHA256 checksums
        command: sha256sum anycable-go-* > SHA256SUM
    - run:
        name: Install ghr tool
        command: env GO111MODULE=off go get github.com/tcnksm/ghr
    - run:
        name: Upload GitHub release
        command: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -prerelease -delete ${CIRCLE_TAG} ./
