name: Push Stable

on:
  workflow_dispatch:

jobs:
  push-1-0-stable:
    if: ${{ contains(github.ref, 'refs/tags/v1.0.') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 1-0-stable
        force: true
  push-1-1-stable:
    if: ${{ contains(github.ref, 'refs/tags/v1.1.') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 1-1-stable
        force: true
